"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
#import macholib_patch

APP = ['labTOF_main.py']
DATA_FILES = ['read_lecroy_binary.py']
OPTIONS = {'includes': ['pkg_resources.resource_filename', 'tkinter_filedialog', 'tkFileDialog', 'matplotlib.pyplot', 'matplotlib.backends.backend_tkagg', 'six.moves']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
